### ISSUE TITLE
End rod pistons don't work with slime blocks.

### ISSUE THREAD

**Issue by Aeltumn** [TheLuca98/Automate#1]
![Image](http://i65.tinypic.com/21nkrab.png)

I feel the end rods should still break the block even if the end rod isn't directly attached to the piston.

**Comment by TheLuca98** [comment]
Given that a slime block should be 'elastic', I don't know whether it being able to 'crush' blocks is expected behaviour 🤔

**Comment by Aeltumn** [comment]
I think it's gameplay against realism. It's more logical and consistent if the rods break anything in front of them when pushed.

**Comment by TheLuca98** [comment]
Fixed!
