### ISSUE TITLE
End rod pistons still push the remaining blocks in front of the piston.

### ISSUE THREAD

**Issue by Aeltumn** [TheLuca98/Automate#2]
![Image](http://i66.tinypic.com/9lgzlk.png) 
When a piston with end rod pushes a stack of blocks the block is broken but the remaining blocks are also pushed forward giving the result in the image.

**Comment by TheLuca98** [comment]
I could revert it to the previous behaviour where the "breaking" would be triggered if there was only 1 block after the end rod; I don't think there's a way to prevent other blocks from being moved which doesn't require a hacky workaround.

**Comment by TheLuca98** [comment]
I'm going to close this as a "won't fix". While the current behavior is certainly not perfect, I don't think it's a good idea to fool around with pistons any more than necessary, as they are already quirky enough (especially with Bukkit).

As always, PRs are welcome, but they will need to be thoroughly tested.
