### ISSUE TITLE
Dispensers can place blocks that should't be placeable.

### ISSUE THREAD

**Issue by Aeltumn** [TheLuca98/Automate#3]
See the example on the right of the image:
![Image](http://i67.tinypic.com/oko9dc.png)
You can see the cactus is placed whilst cacti can't be placed on dirt. There should be a check (maybe by throwing the PlayerPlaceBlock event) to see if the block is allowed to be placed.

**Comment by Aeltumn** [comment]
This also happens for saplings when the dispenser is facing up.

**Comment by TheLuca98** [comment]
One possible solution is to limit placeable blocks through `Material#isSolid()`. I don't know whether that would be too restrictive though.

**Comment by Aeltumn** [comment]
Hmmm.. I don't think that'd work, `Material#isSolid()` is meant for rendering/collision purposes, not for placement. I don't know if you can fake the BlockPlaceEvent and examine its results.

**Comment by TheLuca98** [comment]
The only two options are either to implement a list of placeable blocks, which I'd rather not do, or to use `Material#isSolid()` as a rough approximation.

**Comment by TheLuca98** [comment]
I've decided to make this feature configurable: users will be able to specify in the config file which blocks should be placeable and which should retain vanilla behavior.
